name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create_builddir
      run: mkdir build
    - name: cmake
      run: cmake ..
      working-directory: ./build
    - name: build
      run: cmake --build . -j $(nproc)
      working-directory: ./build
    - name: tests
      run: ./build/tests/UtilTests
