name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: 'recursive'
    - name: create_builddir
      run: mkdir -p build
    - name: cmake
      run: cmake ..
      working-directory: ./build
    - name: build
      run: cmake --build . -j $(nproc) --target UtilsTests
      working-directory: ./build
    - name: tests
      run: ./build/tests/UtilsTests
