name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run:  mkdir build
    - name: cmake
      run: cmake ..
    - name: build
      run: cmake --build .. -j $(nproc)
    - name: tests
      run: ./tests/UtilTests
